from dataclasses import replace
from datetime import UTC, datetime, timedelta
from zoneinfo import ZoneInfo

import pytest
import yaml

from tipipeline.models import ActPhase, HuntPackage
from tipipeline.report import generate
from tipipeline.report.data import snapshot_from_context
from tipipeline.report.digest import build_profile_digest, digest_window, window_documents, window_label
from tipipeline.report.markdown import hunt_markdown
from tipipeline.report.text import defang, md_fence, md_inline, safe_url


def test_reports_render_complete_packages(sample_ctx, sample_now):
    stats = generate(sample_ctx, now=sample_now)
    assert stats["documents"] == 7
    assert stats["hunts"] == 5
    assert stats["digests"] == 3
    brief = (sample_ctx.output_dir / "reports/documents/1.md").read_text()
    for expected in ["Exploit Public-Facing Application", "INVALID ID", "verified", "unverified", "stated", "inferred", "198.51.100.42".replace(".", "[.]"), "hxxps://updates-example[.]net/stage.ps1", "Warninglist", "Microsoft services", "Related reporting", "Relevance by profile", "method: llm"]:
        assert expected in brief
    assert "https://updates-example.net/stage.ps1" not in brief.split("## Indicators", 1)[1]
    kev = (sample_ctx.output_dir / "reports/documents/3.md").read_text()
    assert "method: rules" in kev
    assert "Remediation due" in kev
    law_hunt = next((sample_ctx.output_dir / "hunts/law-firm").glob("1-*.md"))
    hunt_text = law_hunt.read_text()
    for expected in ["## Prepare", "## Execute", "## Act", "## Knowledge", "not run", "pending", "Are actors exploiting our remote-access edge?", "```kusto", "generated by: template", "generated by: llm", "Detection proposals"]:
        assert expected in hunt_text
    data = yaml.safe_load(law_hunt.with_suffix(".yaml").read_text())
    HuntPackage.model_validate({k: v for k, v in data.items() if k != "queries"})
    assert {q["generated_by"] for q in data["queries"]} == {"template", "llm"}
    assert "\n" in data["queries"][0]["kql"]
    assert data["queries"][0]["validation"]["status"] == "schema_valid"
    invalid_yaml = yaml.safe_load(next((sample_ctx.output_dir / "hunts/retail-bank").glob("2-*.yaml")).read_text())
    assert any(q["validation"]["status"] == "invalid" for q in invalid_yaml["queries"])
    digest = (sample_ctx.output_dir / "reports/latest/law-firm.md").read_text()
    for expected in ["## Strategic", "## Operational", "## Tactical", "KEV matches", "CVE-2026-12345", "IOC sweep queries", "output/stix/sentinel-upload/"]:
        assert expected in digest
    assert "Older credential theft report" not in digest
    assert (sample_ctx.output_dir / "reports/digests/2026-10-05-pm/law-firm.md").exists()


def test_hunt_markdown_renders_specific_validation_and_recorded_act_only(sample_ctx, sample_now):
    s = snapshot_from_context(sample_ctx, sample_now)
    law = hunt_markdown(s, s.hunts[1])
    # Schema-valid queries have no validation messages, so nothing sits between metadata and KQL.
    for before in law.split("```kusto")[:-1]:
        assert not before.rstrip().splitlines()[-1].startswith("- ")
    assert "### Recommendations" in law
    assert "### Findings" not in law
    bank = hunt_markdown(s, s.hunts[2])
    assert "- Unknown table: UnconfiguredProcessTable" in bank
    empty = replace(s.hunts[1], package=s.hunts[1].package.model_copy(update={"act": ActPhase()}))
    act = hunt_markdown(s, empty).split("## Act", 1)[1].split("## Knowledge", 1)[0]
    assert "###" not in act
    assert len([line for line in act.splitlines() if line]) == 2


@pytest.mark.parametrize("type_,raw,expected", [
    ("domain", "evil.example.", "evil[.]example[.]"),
    ("ipv4", "198.51.100.42", "198[.]51[.]100[.]42"),
    ("ipv6", "2001:db8::1", "2001[:]db8[:][:]1"),
    ("url", "https://evil.example/a.b?q=x.y", "hxxps://evil[.]example/a.b?q=x.y"),
    ("url", "HTTP://EVIL.EXAMPLE:8080/path", "HXXP://EVIL[.]EXAMPLE:8080/path"),
    ("url", "https://[2001:db8::1]:443/a", "hxxps://[2001[:]db8[:][:]1]:443/a"),
    ("url", "evil.example/path", "evil[.]example/path"),
    ("email", "a.b@evil.example", "a.b[@]evil[.]example"),
    ("sha256", "a"*64, "a"*64),
    ("cve", "CVE-2026-12345", "CVE-2026-12345"),
    ("domain", "", ""),
])
def test_defang_is_nonclickable_and_idempotent(type_, raw, expected):
    assert defang(type_, raw) == expected
    assert defang(type_, expected) == expected


def test_digest_uses_previous_run_start(sample_ctx, sample_now):
    window = digest_window(sample_ctx.db, sample_ctx.run_id, sample_now, ZoneInfo("Europe/London"))
    assert window.start == sample_now - timedelta(hours=12)
    assert window.previous_run_id == 2
    s = snapshot_from_context(sample_ctx, sample_now)
    ids = {d.id for d in window_documents(s, window)}
    assert 7 not in ids  # collected 48h ago
    assert 5 not in ids  # duplicate, not independent corroboration
    assert 1 in ids
    d = build_profile_digest(s, "law-firm", window)
    assert all(i.doc.id != 7 for i in d.items)
    # A deferred older item assessed in this window must not be lost forever.
    sample_ctx.db.execute("UPDATE relevance SET created_at=? WHERE document_id=7", (sample_now.isoformat(),))
    s = snapshot_from_context(sample_ctx, sample_now)
    assert any(i.doc.id == 7 and not i.new_in_window for i in build_profile_digest(s, "law-firm", window).items)


def test_digest_fallback_and_london_ampm(empty_ctx, sample_now):
    window = digest_window(empty_ctx.db, None, sample_now, ZoneInfo("Europe/London"))
    assert window.start == sample_now - timedelta(hours=24)
    assert window.previous_run_id is None
    assert window.label == "2026-10-05-pm"
    # BST changes the AM/PM boundary relative to UTC.
    assert window_label(datetime(2026, 10, 5, 11, 30, tzinfo=UTC), ZoneInfo("Europe/London")) == "2026-10-05-pm"
    assert window_label(datetime(2026, 10, 5, 10, 30, tzinfo=UTC), ZoneInfo("Europe/London")) == "2026-10-05-am"
    # DST rollover also changes the date correctly.
    assert window_label(datetime(2026, 10, 24, 23, 30, tzinfo=UTC), ZoneInfo("Europe/London")) == "2026-10-25-am"


def test_markdown_safety_and_fences(sample_ctx, sample_now):
    generate(sample_ctx, now=sample_now)
    text = (sample_ctx.output_dir / "reports/documents/6.md").read_text()
    assert "<script>" not in text
    assert "\\<script\\>" in text
    assert "\\[click\\]" in md_inline("[click](javascript:alert(1)) | <img>")
    assert "\\|" in md_inline("a|b")
    assert safe_url("javascript:alert(1)") is None
    assert safe_url('https://example.com/\" onclick=evil') is None
    assert md_fence("````\n<script>", "kusto").startswith("`````kusto\n")


def test_empty_database_reports_honest_states(empty_ctx, sample_now):
    stats = generate(empty_ctx, now=sample_now)
    assert stats["documents"] == stats["hunts"] == 0
    text = (empty_ctx.output_dir / "reports/latest/law-firm.md").read_text()
    assert "No high- or medium-priority intelligence" in text
    assert "No hunt packages prepared" in text
    assert "No indicators extracted" in text
    assert "No Sentinel upload batches available" in text
    assert "No IOC sweep queries" in text


def test_rerun_replaces_renamed_hunt_outputs(sample_ctx, sample_now):
    generate(sample_ctx, now=sample_now)
    previous = next((sample_ctx.output_dir / "hunts/law-firm").glob("1-*.md"))
    sample_ctx.db.execute("UPDATE hunts SET title='Renamed hunt' WHERE id=1")
    generate(sample_ctx, now=sample_now)
    assert not previous.exists()
    assert (sample_ctx.output_dir / "hunts/law-firm/1-renamed-hunt.md").exists()
    assert sample_ctx.llm.prompts == []
